version: "3"

services:

  mongo:
    image: mongo
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: always

  hello-microservice:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 3.10-bullseye
        NODE_VERSION: lts/*
    depends_on:
      - mongo
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      # Mounts the project folder to '/workspace'. The target path inside the container
      # should match what your application expects. In this case, the compose file is
      # in a sub-folder, so you will mount '..'. You would then reference this path as the
      # 'workspaceFolder' in '.devcontainer/devcontainer.json' so VS Code starts here.
      - ..:/workspace:cached
    user: vscode
    environment:
      - PYTHONUNBUFFERED=1
      - MODE=dev
      - MONGO_URL=mongo
      - MONGO_PORT=27017
      - SERVER_URL=0.0.0.0
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=pass
      - PORT=2020

    ports:
      - "2020:2020"
